name: Network

on:
  push:
    branches:
      - master
  pull_request: 
    branches:
      - master

jobs:
  build:
    env:
      libs_dir: ${{ github.workspace }}/libs
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          -
            name: "MacOS"
            os: macos-latest
          -
            name: "Windows"
            os: windows-latest
          -
            name: "Ubuntu"
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Cache
        id: cache-testing-lib
        uses: actions/cache@v2
        with:
          key: ${{ matrix.config.os }}-libs
          path: ${{ env.libs_dir }}
      -
        name: Prepare
        if: steps.cache-testing-lib.outputs.cache-hit != 'true'
        env:
          catch_dir: ${{ github.workspace }}/Catch2
          catch_build_dir: ${{ github.workspace }}/Catch2/build
        run: |
          git clone https://github.com/catchorg/Catch2 --depth=1
          cmake -S ${{ env.catch_dir }} -B ${{ env.catch_build_dir }} -DCATCH_BUILD_TESTING=OFF -DCATCH_INSTALL_DOCS=OFF -DCMAKE_INSTALL_PREFIX=${{ env.libs_dir }}
          cmake --build ${{ env.catch_build_dir }}
          cmake --install ${{ env.catch_build_dir }}
      -
        name: Configure
        run: cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release -DNETWORK_BUILD_TESTS=ON -DCMAKE_PREFIX_PATH=${{ env.libs_dir }}
      -
        name: Build
        run: cmake --build ${{ github.workspace }}/build --config Release
      -
        name: Test
        working-directory: ${{ github.workspace }}/build/tests
        run: ctest -C Release
      -
        name: Print
        if: failure()
        working-directory: ${{ github.workspace }}/build/tests
        run: cat *.xml
      -
        name: Codecov
        uses: codecov/codecov-action@v1.0.11
        with:
          name: Network
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "*.xml"
          fail_ci_if_error: echo "Upload is failed"
